### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by santony85** [nicmosc/brick-builder#4] opened 2018-12-08 20:03 UTC
Hello !
How to run production mode ?
Working fine in dev mode but i can't start production.

Thank you

**Comment by nicmosc** [comment] 2019-01-01 19:14
Hi! Sorry for only seeing this now, didn’t check notifications due to holidays. I haven’t actually set up the run command for production. For now the production code is built into `docs` (so that I can run the GitHub pages). Normally running a basic server in the `docs` folder will run the app.

You can try `python -m SimpleHTTPServer`, but I’ll add a production command ASAP anyway :)

**Comment by santony85** [comment] 2019-01-21 17:37
Thank you for answer.

I found a bug on scene that i'm trying to correct but your help will welcome.

If i put a simple 4x2 on scene like this
<img width="839" alt="capture d ecran 2019-01-21 a 18 29 42" src="https://user-images.githubusercontent.com/1708245/51490264-09a60880-1dab-11e9-9def-4c276af5663c.png">
i can put another 4x2 on the right row 
<img width="839" alt="capture d ecran 2019-01-21 a 18 29 58" src="https://user-images.githubusercontent.com/1708245/51490327-3fe38800-1dab-11e9-8385-70c1349d8ff9.png">
on both row
<img width="839" alt="capture d ecran 2019-01-21 a 18 30 17" src="https://user-images.githubusercontent.com/1708245/51490422-76210780-1dab-11e9-8229-03481c5cd919.png">

but i can't do that on the left row
<img width="839" alt="capture d ecran 2019-01-21 a 18 30 10" src="https://user-images.githubusercontent.com/1708245/51490361-55f14880-1dab-11e9-8e8b-0c8b5a18aac9.png">

Can you help me please ?

Thank you

**Comment by nicmosc** [comment] 2019-01-21 18:45
@santony85 the issue you're describing is in fact a duplicate of #3. Basically since we use a raycaster to determine where the intersection of the two (or more) bricks will be, sometimes the placement can be a bit awkward. To fix this during usage you can try and rotate the camera to another angle so that the brick is properly intersected. Otherwise feel free to use a different intersection method as mentioned in #3 :)

**Comment by nicmosc** [comment] 2019-01-21 18:49
@santony85 about the production build, I've updated the readme to contain what I mentioned you before, about having a simple server to serve the static files (https://github.com/nicmosc/brick-builder/commit/f03b8014b78175635c007e0439236c29b996cb4d). If you have some more problems let me know.

I'll close this issue for now

**Closed as completed by nicmosc** 2019-01-21 18:49 UTC
